### ISSUE TITLE
Infinite loop in while from Image.php

### ISSUE THREAD

**Issue by brunonic** [thephpleague/color-extractor#26] opened 2015-02-19 15:49 UTC
Hi,

Got an infinite loop on ligne 129 of Image.php for some images.
Image size is 50*50.

As you can see on my PR, this https://github.com/thephpleague/color-extractor/pull/25 fix the thing.

Any idea ?

Thx

**Comment by MatTheCat** [comment] 2015-02-24 23:55
Hi,

could you put here one of the images?

Thanks.

**Comment by brunonic** [comment] 2015-02-25 06:51
I just send you a mail with the link. I cant put it here.

Thanks

**Comment by MatTheCat** [comment] 2015-02-25 08:32
Thanks I'll take a look as soon as possible.

**Comment by matason** [comment] 2015-03-01 19:57
Hi @brunonic, I knew it would be a long shot but I just created a few 50px x 50px PNG files to see if I could reproduce the infinite loop you reported but couldn't so I guess it's something peculiar about the image you're using that triggers the condition...

**Comment by MatTheCat** [comment] 2015-03-01 22:38
I'm investigating right now. It seems the problem occurs when only one color is requested.

**Comment by MatTheCat** [comment] 2015-03-01 23:05
Okay I see where the problem is. When extracting only one color the minimum deltaE is so big that *all* the image colors are merged and there is no condition to stop the loop in this case.
Additionally there is no need for any merge if only one color is extracted.
I'll close #25 as it doesn't solve the problem and provide a fix.

**Comment by MatTheCat** [comment] 2015-03-01 23:31
Fixed in 8691f1bbca96f2b7e376729aa07d1c80c0afaab0

**Closed by MatTheCat** 2015-03-01 23:31 UTC

**Comment by zandzpider** [comment] 2015-03-02 22:57
Awesome. had a similar issue and the fix solved it! yey!

**Comment by brunonic** [comment] 2015-03-03 07:30
Thanks for the fix. Solved
