### ISSUE TITLE
Use with Image Intervetion

### ISSUE THREAD

**Issue by shardick** [thephpleague/color-extractor#71] opened 2022-02-19 12:08 UTC
Using `Palette::fromGD` with Image Intervetion throw exception "Image must be a gd resource"

Tried with `$image->getCore()` (https://image.intervention.io/v2/api/get-core) that returns a `GdImage` object.

**Comment by MatTheCat** [comment] 2022-08-13 17:06
Yep, duplicate of https://github.com/thephpleague/color-extractor/issues/64

**Closed by MatTheCat** 2022-08-13 17:06 UTC
